# Generated by Django 4.1.4 on 2024-02-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_record_result_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatars',
            options={'verbose_name_plural': ' 图片管理'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name_plural': '历史记录'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='record',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='result_url',
            field=models.CharField(max_length=256, null=True, verbose_name='分割结果'),
        ),
    ]
